default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root_user
  password: root_user
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: referral_mate_development

test:
  <<: *default
  database: referral_mate_test

production:
  <<: *default
  database: referral_mate_production
  username: referral_mate
  password: <%= ENV["REFERRAL_MATE_DATABASE_PASSWORD"] %>
